// Generate the shared subset from the already pinned, licensed Lucide distribution.
const fs = require('node:fs');
const assert = require('node:assert/strict');
const lucide = require('../tool-apps/image-workbench/vendor/lucide.min.js');
const names = new Set();
const apps = ['image-workbench', 'pdf-page-manager', 'qr-workbench'];
function exportName(name) {
    return name.replace(/(^|-)([a-z0-9])/g, (_, separator, letter) => letter.toUpperCase());
}
for (const app of apps) {
    for (const file of ['index.html', 'app.js']) {
        const source = fs.readFileSync('tool-apps/' + app + '/' + file, 'utf8');
        for (const match of source.matchAll(/["']([a-z][a-z0-9-]*)["']/g)) {
            if (Array.isArray(lucide[exportName(match[1])])) names.add(match[1]);
        }
        for (const match of source.matchAll(/data-lucide="([^"]+)"/g)) {
            assert(names.has(match[1]), 'Unknown icon: ' + match[1]);
        }
    }
}
const icons = Object.fromEntries(Array.from(names).sort().map(name => [name, lucide[exportName(name)]]));
const source = `// Generated by scripts/build_tool_icons.js. Lucide 0.468.0, ISC license.
// License: /tool-apps/image-workbench/vendor/lucide.LICENSE
(function() {
    const icons = ${JSON.stringify(icons)};
    function node(spec) {
        const element = document.createElementNS('http://www.w3.org/2000/svg', spec[0]);
        Object.entries(spec[1]).forEach(function(pair) { element.setAttribute(pair[0], pair[1]); });
        (spec[2] || []).forEach(function(child) { element.appendChild(node(child)); });
        return element;
    }
    window.lucide = Object.freeze({ createIcons: function() {
        document.querySelectorAll('i[data-lucide]').forEach(function(placeholder) {
            const name = placeholder.dataset.lucide;
            if (!icons[name]) return;
            const svg = node(icons[name]);
            Array.from(placeholder.attributes).forEach(function(attribute) { svg.setAttribute(attribute.name, attribute.value); });
            svg.classList.add('lucide', 'lucide-' + name);
            placeholder.replaceWith(svg);
        });
    } });
})();
`;
const target = 'assets/js/tool-icons.js';
if (process.argv.includes('--check')) assert.equal(fs.readFileSync(target, 'utf8'), source, 'Run node scripts/build_tool_icons.js');
else fs.writeFileSync(target, source);
console.log('Validated ' + names.size + ' tool icons, ' + Buffer.byteLength(source) + ' bytes.');
